baseURL = "https://louisandrada.com/"
languageCode = "en-us"
title = "Louis Andrada"
theme = "portfolio-theme"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[permalinks]
  artworks = "/artworks/:contentbasename/"
  archive  = "/archive/:contentbasename/"

[outputs]
  home = ["HTML", "RSS"]

[params]
  recaptcha_site_key = "6LcOzL8sAAAAAAf811mO6GNulTWREGNzkzxTScVk"
  webhook_url = "https://script.google.com/macros/s/AKfycbxxnqf8ImE2r9tkV60_7cIQJC4TvdzyDrDc0MovRvk9m4cN_lEntF1LS1EFV5VHmd19/exec"